# Generated by Django 5.1.2 on 2026-06-20 11:15

import compat
import django.db.models.deletion
import mptt.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title_uz",
                    models.CharField(max_length=255, verbose_name="Title (Uzbek)"),
                ),
                (
                    "title_ru",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (Russian)"
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    compat.VersatileImageField(
                        blank=True, null=True, upload_to="categories/icons/"
                    ),
                ),
                (
                    "image",
                    compat.VersatileImageField(
                        blank=True, null=True, upload_to="categories/images/"
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="categories.category",
                        verbose_name="Parent Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_uz", models.CharField(max_length=255)),
                ("title_ru", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "price_from",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "price_to",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=60)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "db_table": "services",
                "ordering": ["sort_order"],
            },
        ),
    ]
