# Generated by Django 5.1.2 on 2026-06-20 11:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_text", models.TextField()),
                ("detected_category", models.CharField(blank=True, max_length=255)),
                ("detected_subcategory", models.CharField(blank=True, max_length=255)),
                (
                    "price_estimate_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "price_estimate_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("estimated_duration", models.CharField(blank=True, max_length=100)),
                (
                    "confidence_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("suggested_masters_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChatLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("response", models.TextField()),
                ("intent", models.CharField(blank=True, max_length=255)),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_chat_logs",
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("reason", models.TextField(blank=True)),
                ("is_clicked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_recommendations",
            },
        ),
        migrations.CreateModel(
            name="FraudDetectionResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("order", "Order"),
                            ("review", "Review"),
                            ("payment", "Payment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(max_length=255)),
                (
                    "score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("is_fraudulent", models.BooleanField(default=False)),
                ("reasons", models.JSONField(blank=True, default=list)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fraud_detection_results",
            },
        ),
    ]
