FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    gcc libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ .

CMD ["celery", "-A", "config", "worker", "-l", "info", "-B", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler", "--concurrency=8", "--max-tasks-per-child=1000"]
