# Generated by Django 5.1.2 on 2026-06-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="response",
            field=models.TextField(blank=True, verbose_name="Response"),
        ),
    ]
